swagger: "2.0"
info:
  version: 1.0.0
  title: YACME (Yet Another Config Management Engine) component contract
  description: The API contract stub for YACME components. All components will conform to this API shape, but vary in input parameters

consumes:
  - application/vnd.api+json
produces:
  - application/vnd.api+json
tags:
  - name: component
    description: Component creation
  - name: docs
    description: Documentation endpoints
paths:
  /:
    post:
      summary: Create a set of component actions
      description: Create a new instance of a component and get back a set of concourse objects for performing actions
      tags: 
        - component
      parameters:
        - in: body
          name: params
          type: object
          required: true
          description: Filled out parameter set as described in /definition
      responses:
        201:
          description: Created
          responses:
            schema:
              $ref: "#/definitions/component_actions"
        400:
          description: Bad input parameters. Check /definition for available params


  /definition:
    get:
      summary: Object data structure definition
      tags:
        - docs
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/component_definition"
  /docs:
    get:
      summary: API Docs
      description: Swagger formatted API json.
      tags:
        - docs
      responses:
        200:
          description: OK

definitions:
  errors:
    properties:
      errors:
        type: array

  component_definition:
    type: object
    properties:
      class:
        type: string
        enum:
          - object
          - action
        example: object
      type:
        type: string
        example: RDS-PG
      name:
        type: string
        example: RDS-backed postgres
      params:
        type: object
        example:
          PD_USERNAME: string
          PG_PASSWORD: string
          PG_HOST: string
          PG_PORT: integer

  component_actions:
    type: array
    items:
      type: object
      properties:
        action:
          type: string
          enum:
            - create
            - check
            - update
            - destroy
        resource:
          type: object
        job:
          type: object
