swagger: "2.0"
info:
  version: 1.0.0
  title: YACME (Yet Another Config Management Engine) component contract
  description: The API contract stub for YACME components. All components will conform to this API shape, but vary in input parameters

consumes:
  - application/vnd.api+json
produces:
  - application/vnd.api+json
tags:
  - name: component
    description: Component creation
  - name: docs
    description: Documentation endpoints
paths:
  /:
    post:
      summary: Create a set of component actions
      description: Create a new instance of a component and get back a set of concourse objects for performing actions
      tags: 
        - component
      parameters:
        - in: body
          name: params
          type: object
          required: true
          description: Filled out parameter set as described in /definition
          example:
            PD_USERNAME: root
            PG_PASSWORD: root-pass
            PG_HOST: postgres.internal.example.com
            PG_PORT: 5432
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/component_actions"
        400:
          description: Bad input parameters. Check /definition for available params


  /definition:
    get:
      summary: Object data structure definition
      tags:
        - docs
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/component_definition"
  /docs:
    get:
      summary: API Docs
      description: Swagger formatted API json.
      tags:
        - docs
      responses:
        200:
          description: OK

definitions:
  errors:
    properties:
      errors:
        type: array
        items:
          type: string
      description: List of errors

  component_definition:
    type: object
    properties:
      class:
        type: string
        enum:
          - object
          - action
        example: object
        description: |
          * `object` - object components are centered around a resource definition that needs to be managed and should include `create`, `check`, `update`, and `delete` actions.
          * `action` - an action component is just that: a concourse step/job that gets executed (`execute` action)
      name:
        type: string
        example: RDS-backed postgres
        description: |
          Unique name for the component. 
      params:
        type: object
        example:
          PD_USERNAME: string
          PG_PASSWORD: string
          PG_HOST: string
          PG_PORT: integer
        description: |
          Param set needed to define and interact with the component
      description:
        type: string
        description: The description of the component

  component_actions:
    type: array
    items:
      type: object
      properties:
        action:
          type: string
          enum:
            - create
            - check
            - update
            - delete
            - execute
          description: |
            Object actions: lifecycle management concnourse actions for an object

            * `create` - concnourse step to create the object
            * `check`  - concnourse step to check on object status
            * `update` - concnourse step to update object
            * `delete`- concnourse step to delete the resource

            Action actions: 
            * `execute` - definition of the concourse action
        resource_types:
          type: array
          items:
            type: object
          description: Concourse resource types associated with the component action
        resources:
          type: array
          items:
            type: object
          description: Concourse resources associated with the component action
        jobs:
          type: array
          items:
            type: object
          description: Concourse jobs associated with the component action
